# Generated by Django 4.2.3 on 2023-08-01 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advertisements',
            new_name='Advertisement',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='desription',
            new_name='description',
        ),
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
